### ISSUE TITLE
Formatting issues when used in conjunction with Moment.js

### ISSUE THREAD

**Issue by samajammin** [kraynel/gatsby-transformer-gitinfo#22]
First off, thank you for creating this plugin!

I'm seeing this warning message when querying the `gitLogLatestDate` then attempting to use this timestamp with moment:

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2020-06-25 12:37:24 -0700, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:29334:25)
    at configFromString (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:31551:19)
    at configFromInput (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:31993:13)
    at prepareConfig (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:31976:13)
    at createFromConfig (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:31943:44)
    at createLocalOrUTC (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:32037:16)
    at createLocal (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:32041:16)
    at hooks (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:29031:29)
    at getLocaleTimestamp (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:63200:192)
    at StaticPage (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:63184:892)
    at d (/Users/samrichards/code/ef/ethereum-org-website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/Users/samrichards/code/ef/ethereum-org-website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/samrichards/code/ef/ethereum-org-website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/samrichards/code/ef/ethereum-org-website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/samrichards/code/ef/ethereum-org-website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Module../.cache/static-entry.js.__webpack_exports__.default (/Users/samrichards/code/ef/ethereum-org-website/public/render-page.js:625:28)
```

Here's the code that triggers the warning (`timestamp` is the `gitLogLatestDate` field from a graphql query):
```
  moment.locale(locale)
  return moment(timestamp).format("MMM DD, YYYY")
```

Looking at [Moment's docs](http://momentjs.com/guides/#/warnings/js-date/ ), they instruct "specify a format for the string being passed to `moment()`." - what is the format of the `gitLogLatestDate` field?

**Comment by CollierCZ** [comment]
@samajammin , it looks like you resolved this, but in case not, Gatsby uses Moment. So you can [pull it as any format](https://harrycresswell.com/notes/formatting-dates-gatsby/) from the GraphQL query. By default, it's the `ISO 8601-like format` from git.
